/**
 * 每日集卡功能 - 卡牌配置数据
 */

// 传统元素卡牌（52张）
export const TRADITIONAL_CARDS = [
  // 黑桃 - 生肖系列（12张）
  {
    id: 'rat',
    name: '子鼠',
    englishName: 'Rat',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'water',
    description: '聪明机智，灵活应变',
    icon: '🐭'
  },
  {
    id: 'ox',
    name: '丑牛',
    englishName: 'Ox',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'earth',
    description: '勤劳踏实，坚韧不拔',
    icon: '🐮'
  },
  {
    id: 'tiger',
    name: '寅虎',
    englishName: 'Tiger',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SR',
    element: 'wood',
    description: '勇猛果敢，威严霸气',
    icon: '🐯'
  },
  {
    id: 'rabbit',
    name: '卯兔',
    englishName: 'Rabbit',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'wood',
    description: '温柔敏捷，机智聪明',
    icon: '🐰'
  },
  {
    id: 'dragon',
    name: '辰龙',
    englishName: 'Dragon',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SSR',
    element: 'earth',
    description: '腾云驾雾，威震四方',
    icon: '🐉'
  },
  {
    id: 'snake',
    name: '巳蛇',
    englishName: 'Snake',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SR',
    element: 'fire',
    description: '神秘智慧，灵活多变',
    icon: '🐍'
  },
  {
    id: 'horse',
    name: '午马',
    englishName: 'Horse',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SR',
    element: 'fire',
    description: '奔腾不息，勇往直前',
    icon: '🐎'
  },
  {
    id: 'sheep',
    name: '未羊',
    englishName: 'Sheep',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'earth',
    description: '温顺善良，富有同情心',
    icon: '🐑'
  },
  {
    id: 'monkey',
    name: '申猴',
    englishName: 'Monkey',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SR',
    element: 'metal',
    description: '机智灵活，聪明伶俐',
    icon: '🐵'
  },
  {
    id: 'rooster',
    name: '酉鸡',
    englishName: 'Rooster',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'metal',
    description: '勤奋守时，自信热情',
    icon: '🐓'
  },
  {
    id: 'dog',
    name: '戌狗',
    englishName: 'Dog',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'R',
    element: 'earth',
    description: '忠诚可靠，勇敢直率',
    icon: '🐕'
  },
  {
    id: 'pig',
    name: '亥猪',
    englishName: 'Pig',
    type: 'zodiac',
    suit: 'spade',
    suitSymbol: '♠️',
    rarity: 'SR',
    element: 'water',
    description: '诚实善良，宽宏大量',
    icon: '🐷'
  },

  // 红心 - 节气系列（12张）
  {
    id: 'lichun',
    name: '立春',
    englishName: 'Beginning of Spring',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'spring',
    description: '春回大地，万物复苏',
    icon: '🌱'
  },
  {
    id: 'yushui',
    name: '雨水',
    englishName: 'Rain Water',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'spring',
    description: '春雨绵绵，滋润万物',
    icon: '🌧️'
  },
  {
    id: 'jingzhe',
    name: '惊蛰',
    englishName: 'Awakening of Insects',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'spring',
    description: '春雷乍响，万物生长',
    icon: '⚡'
  },
  {
    id: 'chunfen',
    name: '春分',
    englishName: 'Spring Equinox',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'spring',
    description: '昼夜平分，春意盎然',
    icon: '🌸'
  },
  {
    id: 'qingming',
    name: '清明',
    englishName: 'Qingming',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'spring',
    description: '清明时节，春意正浓',
    icon: '🌿'
  },
  {
    id: 'guyu',
    name: '谷雨',
    englishName: 'Grain Rain',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'spring',
    description: '雨生百谷，春意盎然',
    icon: '🌾'
  },
  {
    id: 'lixia',
    name: '立夏',
    englishName: 'Beginning of Summer',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'summer',
    description: '夏日初临，绿意盎然',
    icon: '☀️'
  },
  {
    id: 'xiaoman',
    name: '小满',
    englishName: 'Grain Full',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'summer',
    description: '麦穗渐满，夏日初长',
    icon: '🌾'
  },
  {
    id: 'mangzhong',
    name: '芒种',
    englishName: 'Grain in Ear',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'summer',
    description: '芒种时节，农忙正酣',
    icon: '🌾'
  },
  {
    id: 'xiazhi',
    name: '夏至',
    englishName: 'Summer Solstice',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'summer',
    description: '日长至极，盛夏如歌',
    icon: '🌞'
  },
  {
    id: 'xiaoshu',
    name: '小暑',
    englishName: 'Minor Heat',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'R',
    season: 'summer',
    description: '暑气渐起，夏日炎炎',
    icon: '🔥'
  },
  {
    id: 'dashu',
    name: '大暑',
    englishName: 'Major Heat',
    type: 'solar_term',
    suit: 'heart',
    suitSymbol: '♥️',
    rarity: 'SR',
    season: 'summer',
    description: '酷暑盛夏，烈日炎炎',
    icon: '☀️'
  },

  // 方片 - 时辰系列（12张）
  {
    id: 'zishi',
    name: '子时',
    englishName: 'Zi Hour',
    alias: '夜半',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'SR',
    time: '23:00-01:00',
    description: '夜半，静谧如水',
    icon: '🌙'
  },
  {
    id: 'choushi',
    name: '丑时',
    englishName: 'Chou Hour',
    alias: '鸡鸣',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '01:00-03:00',
    description: '鸡鸣，黎明将至',
    icon: '🐓'
  },
  {
    id: 'yinshi',
    name: '寅时',
    englishName: 'Yin Hour',
    alias: '平旦',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '03:00-05:00',
    description: '平旦，日出东方',
    icon: '🌅'
  },
  {
    id: 'maoshi',
    name: '卯时',
    englishName: 'Mao Hour',
    alias: '日出',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '05:00-07:00',
    description: '日出，万物苏醒',
    icon: '🌅'
  },
  {
    id: 'chenshi',
    name: '辰时',
    englishName: 'Chen Hour',
    alias: '食时',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '07:00-09:00',
    description: '食时，朝阳初升',
    icon: '🍽️'
  },
  {
    id: 'sishi',
    name: '巳时',
    englishName: 'Si Hour',
    alias: '隅中',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'SR',
    time: '09:00-11:00',
    description: '隅中，阳光明媚',
    icon: '☀️'
  },
  {
    id: 'wushi',
    name: '午时',
    englishName: 'Wu Hour',
    alias: '日中',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'SR',
    time: '11:00-13:00',
    description: '日中，烈日当空',
    icon: '☀️'
  },
  {
    id: 'weishi',
    name: '未时',
    englishName: 'Wei Hour',
    alias: '日昳',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '13:00-15:00',
    description: '日昳，骄阳似火',
    icon: '🌤️'
  },
  {
    id: 'shenshi',
    name: '申时',
    englishName: 'Shen Hour',
    alias: '哺时',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '15:00-17:00',
    description: '哺时，夕阳西下',
    icon: '🌇'
  },
  {
    id: 'youshi',
    name: '酉时',
    englishName: 'You Hour',
    alias: '日入',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '17:00-19:00',
    description: '日入，暮色渐浓',
    icon: '🌇'
  },
  {
    id: 'xushi',
    name: '戌时',
    englishName: 'Xu Hour',
    alias: '黄昏',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'SR',
    time: '19:00-21:00',
    description: '黄昏，夜幕降临',
    icon: '🌆'
  },
  {
    id: 'haishi',
    name: '亥时',
    englishName: 'Hai Hour',
    alias: '人定',
    type: 'hour',
    suit: 'diamond',
    suitSymbol: '♦️',
    rarity: 'R',
    time: '21:00-23:00',
    description: '人定，夜色正浓',
    icon: '🌃'
  },

  // 梅花 - 四季系列（16张）
  {
    id: 'chunfeng',
    name: '春风',
    englishName: 'Spring Wind',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'R',
    season: 'spring',
    description: '春风拂面，万物复苏',
    icon: '🌬️'
  },
  {
    id: 'chunyu',
    name: '春雨',
    englishName: 'Spring Rain',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'R',
    season: 'spring',
    description: '春雨绵绵，润物无声',
    icon: '🌧️'
  },
  {
    id: 'xialei',
    name: '夏雷',
    englishName: 'Summer Thunder',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'summer',
    description: '夏雷阵阵，气势磅礴',
    icon: '⛈️'
  },
  {
    id: 'xiayu',
    name: '夏雨',
    englishName: 'Summer Rain',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'R',
    season: 'summer',
    description: '夏雨骤降，清凉怡人',
    icon: '🌧️'
  },
  {
    id: 'qiushuang',
    name: '秋霜',
    englishName: 'Autumn Frost',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'autumn',
    description: '秋霜染白，层林尽染',
    icon: '❄️'
  },
  {
    id: 'qiulu',
    name: '秋露',
    englishName: 'Autumn Dew',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'R',
    season: 'autumn',
    description: '秋露凝珠，晶莹剔透',
    icon: '💧'
  },
  {
    id: 'dongxue',
    name: '冬雪',
    englishName: 'Winter Snow',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'winter',
    description: '冬雪纷飞，银装素裹',
    icon: '❄️'
  },
  {
    id: 'dongshuang',
    name: '冬霜',
    englishName: 'Winter Frost',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'R',
    season: 'winter',
    description: '冬霜凝重，寒气逼人',
    icon: '❄️'
  },
  {
    id: 'chenxi',
    name: '晨曦',
    englishName: 'Morning Light',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'all',
    description: '晨曦微露，希望初现',
    icon: '🌅'
  },
  {
    id: 'xiyang',
    name: '夕阳',
    englishName: 'Sunset',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'all',
    description: '夕阳西下，余晖灿烂',
    icon: '🌇'
  },
  {
    id: 'zhaoyang',
    name: '朝阳',
    englishName: 'Morning Sun',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SSR',
    season: 'all',
    description: '朝阳初升，万物迎新',
    icon: '🌄'
  },
  {
    id: 'yueguang',
    name: '月光',
    englishName: 'Moonlight',
    type: 'season',
    suit: 'club',
    suitSymbol: '♣️',
    rarity: 'SR',
    season: 'all',
    description: '月光如水，清辉满地',
    icon: '🌙'
  }
];

// 易经卦象卡牌（64张）- 完整64卦
export const HEXAGRAM_CARDS = [
  // 乾宫八卦
  {
    id: 'qian',
    name: '乾为天',
    englishName: 'Qian',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '乾',
    lowerTrigram: '乾',
    description: '天行健，君子以自强不息',
    icon: '☰',
    卦辞: '元亨利贞'
  },
  {
    id: 'kun',
    name: '坤为地',
    englishName: 'Kun',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '坤',
    lowerTrigram: '坤',
    description: '地势坤，君子以厚德载物',
    icon: '☷',
    卦辞: '元亨利牝马之贞'
  },
  {
    id: 'tun',
    name: '水雷屯',
    englishName: 'Tun',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '坎',
    lowerTrigram: '震',
    description: '屯：元亨利贞',
    icon: '☵☳',
    卦辞: '元亨利贞，勿用有攸往'
  },
  {
    id: 'meng',
    name: '山水蒙',
    englishName: 'Meng',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '艮',
    lowerTrigram: '坎',
    description: '蒙：亨',
    icon: '☶☵',
    卦辞: '亨。匪我求童蒙，童蒙求我'
  },
  {
    id: 'xu',
    name: '水天需',
    englishName: 'Xu',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '坎',
    lowerTrigram: '乾',
    description: '需：有孚，光亨，贞吉',
    icon: '☵☰',
    卦辞: '有孚，光亨，贞吉'
  },
  {
    id: 'song',
    name: '天水讼',
    englishName: 'Song',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '乾',
    lowerTrigram: '坎',
    description: '讼：有孚，窒。惕中吉',
    icon: '☰☵',
    卦辞: '有孚，窒。惕中吉'
  },
  {
    id: 'shi',
    name: '地水师',
    englishName: 'Shi',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坤',
    lowerTrigram: '坎',
    description: '师：贞，丈人，吉无咎',
    icon: '☷☵',
    卦辞: '贞，丈人，吉无咎'
  },
  {
    id: 'bi',
    name: '水地比',
    englishName: 'Bi',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '坎',
    lowerTrigram: '坤',
    description: '比：吉。原筮元永贞，无咎',
    icon: '☵☷',
    卦辞: '吉。原筮元永贞，无咎'
  },
  // 继续添加其他卦象
  {
    id: 'xiaochu',
    name: '风天小畜',
    englishName: 'Xiao Chu',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '巽',
    lowerTrigram: '乾',
    description: '小畜：亨。密云不雨',
    icon: '☴☰',
    卦辞: '亨。密云不雨'
  },
  {
    id: 'lv',
    name: '天泽履',
    englishName: 'Lv',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '兑',
    description: '履：履虎尾，不咥人，亨',
    icon: '☰☱',
    卦辞: '履虎尾，不咥人，亨'
  },
  {
    id: 'tai',
    name: '地天泰',
    englishName: 'Tai',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '坤',
    lowerTrigram: '乾',
    description: '泰：小往大来，吉亨',
    icon: '☷☰',
    卦辞: '小往大来，吉亨'
  },
  {
    id: 'pi',
    name: '天地否',
    englishName: 'Pi',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '坤',
    description: '否：否之匪人，不利君子贞',
    icon: '☰☷',
    卦辞: '否之匪人，不利君子贞'
  },
  {
    id: 'tongren',
    name: '天火同人',
    englishName: 'Tong Ren',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '离',
    description: '同人：同人于野，亨',
    icon: '☰☲',
    卦辞: '同人于野，亨'
  },
  {
    id: 'dayou',
    name: '火天大有',
    englishName: 'Da You',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '离',
    lowerTrigram: '乾',
    description: '大有：元亨',
    icon: '☲☰',
    卦辞: '元亨'
  },
  {
    id: 'qian',
    name: '地山谦',
    englishName: 'Qian',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坤',
    lowerTrigram: '艮',
    description: '谦：亨，君子有终',
    icon: '☷☶',
    卦辞: '亨，君子有终'
  },
  {
    id: 'yu',
    name: '雷地豫',
    englishName: 'Yu',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '震',
    lowerTrigram: '坤',
    description: '豫：利建侯行师',
    icon: '☳☷',
    卦辞: '利建侯行师'
  },
  {
    id: 'sui',
    name: '泽雷随',
    englishName: 'Sui',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '兑',
    lowerTrigram: '震',
    description: '随：元亨利贞，无咎',
    icon: '☱☳',
    卦辞: '元亨利贞，无咎'
  },
  {
    id: 'gu',
    name: '山风蛊',
    englishName: 'Gu',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '艮',
    lowerTrigram: '巽',
    description: '蛊：元亨，利涉大川',
    icon: '☶☴',
    卦辞: '元亨，利涉大川'
  },
  {
    id: 'lin',
    name: '地泽临',
    englishName: 'Lin',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '坤',
    lowerTrigram: '兑',
    description: '临：元亨利贞',
    icon: '☷☱',
    卦辞: '元亨利贞'
  },
  {
    id: 'guan',
    name: '风地观',
    englishName: 'Guan',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '巽',
    lowerTrigram: '坤',
    description: '观：盥而不荐，有孚颙若',
    icon: '☴☷',
    卦辞: '盥而不荐，有孚颙若'
  },
  {
    id: 'shike',
    name: '火雷噬嗑',
    englishName: 'Shi Ke',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '离',
    lowerTrigram: '震',
    description: '噬嗑：亨，利用狱',
    icon: '☲☳',
    卦辞: '亨，利用狱'
  },
  {
    id: 'bi',
    name: '山火贲',
    englishName: 'Bi',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '艮',
    lowerTrigram: '离',
    description: '贲：亨，小利有攸往',
    icon: '☶☲',
    卦辞: '亨，小利有攸往'
  },
  {
    id: 'bo',
    name: '山地剥',
    englishName: 'Bo',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '艮',
    lowerTrigram: '坤',
    description: '剥：不利有攸往',
    icon: '☶☷',
    卦辞: '不利有攸往'
  },
  {
    id: 'fu',
    name: '地雷复',
    englishName: 'Fu',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坤',
    lowerTrigram: '震',
    description: '复：亨，出入无疾',
    icon: '☷☳',
    卦辞: '亨，出入无疾'
  },
  {
    id: 'wuwang',
    name: '天雷无妄',
    englishName: 'Wu Wang',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '震',
    description: '无妄：元亨利贞',
    icon: '☰☳',
    卦辞: '元亨利贞'
  },
  {
    id: 'daxu',
    name: '山天大畜',
    englishName: 'Da Xu',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '艮',
    lowerTrigram: '乾',
    description: '大畜：利贞，不家食吉',
    icon: '☶☰',
    卦辞: '利贞，不家食吉'
  },
  {
    id: 'yi',
    name: '山雷颐',
    englishName: 'Yi',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '艮',
    lowerTrigram: '震',
    description: '颐：贞吉',
    icon: '☶☳',
    卦辞: '贞吉'
  },
  {
    id: 'daguo',
    name: '泽风大过',
    englishName: 'Da Guo',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '兑',
    lowerTrigram: '巽',
    description: '大过：栋桡，利有攸往',
    icon: '☱☴',
    卦辞: '栋桡，利有攸往'
  },
  {
    id: 'xikan',
    name: '习坎',
    englishName: 'Xi Kan',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坎',
    lowerTrigram: '坎',
    description: '习坎：有孚，维心亨',
    icon: '☵☵',
    卦辞: '有孚，维心亨'
  },
  {
    id: 'xili',
    name: '离',
    englishName: 'Xi Li',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '离',
    lowerTrigram: '离',
    description: '离：利贞，亨',
    icon: '☲☲',
    卦辞: '利贞，亨'
  },
  // 咸卦到解卦
  {
    id: 'xian',
    name: '泽山咸',
    englishName: 'Xian',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '兑',
    lowerTrigram: '艮',
    description: '咸：亨，利贞',
    icon: '☱☶',
    卦辞: '亨，利贞'
  },
  {
    id: 'heng',
    name: '雷风恒',
    englishName: 'Heng',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '震',
    lowerTrigram: '巽',
    description: '恒：亨，无咎，利贞',
    icon: '☳☴',
    卦辞: '亨，无咎，利贞'
  },
  {
    id: 'dun',
    name: '天山遁',
    englishName: 'Dun',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '艮',
    description: '遁：亨，小利贞',
    icon: '☰☶',
    卦辞: '亨，小利贞'
  },
  {
    id: 'dazhuang',
    name: '雷天大壮',
    englishName: 'Da Zhuang',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '震',
    lowerTrigram: '乾',
    description: '大壮：利贞',
    icon: '☳☰',
    卦辞: '利贞'
  },
  {
    id: 'jin',
    name: '火地晋',
    englishName: 'Jin',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '离',
    lowerTrigram: '坤',
    description: '晋：康侯用锡马蕃庶',
    icon: '☲☷',
    卦辞: '康侯用锡马蕃庶'
  },
  {
    id: 'mingyi',
    name: '地火明夷',
    englishName: 'Ming Yi',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坤',
    lowerTrigram: '离',
    description: '明夷：利艰贞',
    icon: '☷☲',
    卦辞: '利艰贞'
  },
  {
    id: 'jiaren',
    name: '风火家人',
    englishName: 'Jia Ren',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '巽',
    lowerTrigram: '离',
    description: '家人：利女贞',
    icon: '☴☲',
    卦辞: '利女贞'
  },
  {
    id: 'kui',
    name: '火泽睽',
    englishName: 'Kui',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '离',
    lowerTrigram: '兑',
    description: '睽：小事吉',
    icon: '☲☱',
    卦辞: '小事吉'
  },
  {
    id: 'jian',
    name: '水山蹇',
    englishName: 'Jian',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坎',
    lowerTrigram: '艮',
    description: '蹇：利西南，不利东北',
    icon: '☵☶',
    卦辞: '利西南，不利东北'
  },
  {
    id: 'xie',
    name: '雷水解',
    englishName: 'Xie',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '震',
    lowerTrigram: '坎',
    description: '解：利西南',
    icon: '☳☵',
    卦辞: '利西南'
  },
  // 损卦到萃卦
  {
    id: 'sun',
    name: '山泽损',
    englishName: 'Sun',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '艮',
    lowerTrigram: '兑',
    description: '损：有孚，元吉',
    icon: '☶☱',
    卦辞: '有孚，元吉'
  },
  {
    id: 'yi',
    name: '风雷益',
    englishName: 'Yi',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '巽',
    lowerTrigram: '震',
    description: '益：利有攸往，利涉大川',
    icon: '☴☳',
    卦辞: '利有攸往，利涉大川'
  },
  {
    id: 'guai',
    name: '泽天夬',
    englishName: 'Guai',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '兑',
    lowerTrigram: '乾',
    description: '夬：扬于王庭，孚号',
    icon: '☱☰',
    卦辞: '扬于王庭，孚号'
  },
  {
    id: 'gou',
    name: '天风姤',
    englishName: 'Gou',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '乾',
    lowerTrigram: '巽',
    description: '姤：女壮，勿用取女',
    icon: '☰☴',
    卦辞: '女壮，勿用取女'
  },
  {
    id: 'cui',
    name: '泽地萃',
    englishName: 'Cui',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '兑',
    lowerTrigram: '坤',
    description: '萃：亨，王假有庙',
    icon: '☱☷',
    卦辞: '亨，王假有庙'
  },
  {
    id: 'sheng',
    name: '地风升',
    englishName: 'Sheng',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '坤',
    lowerTrigram: '巽',
    description: '升：元亨，用见大人',
    icon: '☷☴',
    卦辞: '元亨，用见大人'
  },
  {
    id: 'kun',
    name: '泽水困',
    englishName: 'Kun',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '兑',
    lowerTrigram: '坎',
    description: '困：亨，贞，大人吉',
    icon: '☱☵',
    卦辞: '亨，贞，大人吉'
  },
  {
    id: 'jing',
    name: '水风井',
    englishName: 'Jing',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坎',
    lowerTrigram: '巽',
    description: '井：改邑不改井',
    icon: '☵☴',
    卦辞: '改邑不改井'
  },
  {
    id: 'ge',
    name: '泽火革',
    englishName: 'Ge',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '兑',
    lowerTrigram: '离',
    description: '革：己日乃孚，元亨利贞',
    icon: '☱☲',
    卦辞: '己日乃孚，元亨利贞'
  },
  {
    id: 'ding',
    name: '火风鼎',
    englishName: 'Ding',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '离',
    lowerTrigram: '巽',
    description: '鼎：元吉，亨',
    icon: '☲☴',
    卦辞: '元吉，亨'
  },
  {
    id: 'zhen',
    name: '震为雷',
    englishName: 'Zhen',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '震',
    lowerTrigram: '震',
    description: '震：亨，震来虩虩',
    icon: '☳☳',
    卦辞: '亨，震来虩虩'
  },
  {
    id: 'gen',
    name: '艮为山',
    englishName: 'Gen',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '艮',
    lowerTrigram: '艮',
    description: '艮：艮其背，不获其身',
    icon: '☶☶',
    卦辞: '艮其背，不获其身'
  },
  {
    id: 'jian',
    name: '风山渐',
    englishName: 'Jian',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '巽',
    lowerTrigram: '艮',
    description: '渐：女归吉，利贞',
    icon: '☴☶',
    卦辞: '女归吉，利贞'
  },
  {
    id: 'guimei',
    name: '雷泽归妹',
    englishName: 'Gui Mei',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '震',
    lowerTrigram: '兑',
    description: '归妹：征凶，无攸利',
    icon: '☳☱',
    卦辞: '征凶，无攸利'
  },
  {
    id: 'feng',
    name: '雷火丰',
    englishName: 'Feng',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '震',
    lowerTrigram: '离',
    description: '丰：亨，王假之',
    icon: '☳☲',
    卦辞: '亨，王假之'
  },
  {
    id: 'lv',
    name: '火山旅',
    englishName: 'Lv',
    type: 'hexagram',
    rarity: 'R',
    upperTrigram: '艮',
    lowerTrigram: '离',
    description: '旅：小亨，旅贞吉',
    icon: '☶☲',
    卦辞: '小亨，旅贞吉'
  },
  {
    id: 'xun',
    name: '巽为风',
    englishName: 'Xun',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '巽',
    lowerTrigram: '巽',
    description: '巽：小亨，利有攸往',
    icon: '☴☴',
    卦辞: '小亨，利有攸往'
  },
  {
    id: 'dui',
    name: '兑为泽',
    englishName: 'Dui',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '兑',
    lowerTrigram: '兑',
    description: '兑：亨，利贞',
    icon: '☱☱',
    卦辞: '亨，利贞'
  },
  {
    id: 'huan',
    name: '风水涣',
    englishName: 'Huan',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '巽',
    lowerTrigram: '坎',
    description: '涣：亨，王假有庙',
    icon: '☴☵',
    卦辞: '亨，王假有庙'
  },
  {
    id: 'jie',
    name: '水泽节',
    englishName: 'Jie',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '坎',
    lowerTrigram: '兑',
    description: '节：亨，苦节不可贞',
    icon: '☵☱',
    卦辞: '亨，苦节不可贞'
  },
  {
    id: 'zhongfu',
    name: '风泽中孚',
    englishName: 'Zhong Fu',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '巽',
    lowerTrigram: '兑',
    description: '中孚：豚鱼吉，利涉大川',
    icon: '☴☱',
    卦辞: '豚鱼吉，利涉大川'
  },
  {
    id: 'xiaoguo',
    name: '雷山小过',
    englishName: 'Xiao Guo',
    type: 'hexagram',
    rarity: 'SR',
    upperTrigram: '震',
    lowerTrigram: '艮',
    description: '小过：亨，利贞',
    icon: '☳☶',
    卦辞: '亨，利贞'
  },
  {
    id: 'jiji',
    name: '水火既济',
    englishName: 'Ji Ji',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '坎',
    lowerTrigram: '离',
    description: '既济：亨小，利贞',
    icon: '☵☲',
    卦辞: '亨小，利贞'
  },
  {
    id: 'weiji',
    name: '火水未济',
    englishName: 'Wei Ji',
    type: 'hexagram',
    rarity: 'SSR',
    upperTrigram: '离',
    lowerTrigram: '坎',
    description: '未济：亨，小狐汔济',
    icon: '☲☵',
    卦辞: '亨，小狐汔济'
  }
];

// 按稀有度分类的卡牌池
export const CARD_POOLS = {
  traditional: {
    'R': TRADITIONAL_CARDS.filter(c => c.rarity === 'R'),
    'SR': TRADITIONAL_CARDS.filter(c => c.rarity === 'SR'),
    'SSR': TRADITIONAL_CARDS.filter(c => c.rarity === 'SSR')
  },
  hexagram: {
    'R': HEXAGRAM_CARDS.filter(c => c.rarity === 'R'),
    'SR': HEXAGRAM_CARDS.filter(c => c.rarity === 'SR'),
    'SSR': HEXAGRAM_CARDS.filter(c => c.rarity === 'SSR')
  }
};

// 稀有度配置
export const RARITY_CONFIG = {
  'R': {
    label: 'R',
    fullName: 'Rare',
    chineseName: '普通',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #64748b 0%, #94a3b8 100%)',
    probability: 0.70,
    borderSize: '2px',
    shadow: '0 4px 12px rgba(100, 116, 139, 0.3)',
    animation: 'fadeIn 0.5s ease-out'
  },
  'SR': {
    label: 'SR',
    fullName: 'Super Rare',
    chineseName: '稀有',
    color: '#d97706',
    gradient: 'linear-gradient(135deg, #92400e 0%, #f59e0b 100%)',
    probability: 0.25,
    borderSize: '3px',
    shadow: '0 4px 20px rgba(217, 119, 6, 0.5)',
    animation: 'scaleIn 0.6s ease-out'
  },
  'SSR': {
    label: 'SSR',
    fullName: 'Super Super Rare',
    chineseName: '传说',
    color: '#dc2626',
    gradient: 'linear-gradient(135deg, #7c2d12 0%, #f97316 50%, #fbbf24 100%)',
    probability: 0.05,
    borderSize: '4px',
    shadow: '0 6px 30px rgba(220, 38, 38, 0.8)',
    animation: 'flipIn 1.0s ease-out'
  }
};

// 抽卡权重配置
export const DRAW_WEIGHTS = {
  'R': 70,
  'SR': 25,
  'SSR': 5
};

// 每日抽卡限制
export const DAILY_DRAW_LIMIT = 3;

// 保底配置
export const PITY_CONFIG = {
  SR: {
    threshold: 10,
    guaranteed: true
  },
  SSR: {
    threshold: 50,
    guaranteed: true
  }
};

export default {
  TRADITIONAL_CARDS,
  HEXAGRAM_CARDS,
  CARD_POOLS,
  RARITY_CONFIG,
  DRAW_WEIGHTS,
  DAILY_DRAW_LIMIT,
  PITY_CONFIG
};
